version: "3.8"
services:
  petstore-http:
    build:
      context: docker/app
    volumes:
      - ./internal:/internal
      - ./.go/pkg:/go/pkg
      - ./.go-cache:/go-cache
    working_dir: /internal/petstore
    ports:
      - "127.0.0.1:3000:$PORT"
    env_file:
      - .env
    environment:
      GOCACHE: /go-cache
    depends_on:
      - postgres

  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db:
    driver: local
